name: CI/CD Pipeline - Time Series Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_time_series_analysis:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install matplotlib pandas numpy statsmodels scikit-learn

    # Run the Time Series Analysis script
    - name: Run Time Series Analysis
      run: python Time Series Analysis.py  # Ensure this filename matches your script

    # Upload generated plots as artifacts
    - name: Upload Time Series Plots
      uses: actions/upload-artifact@v4
      with:
        name: time-series-plots
        path: output/
