name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests (optional)
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
    
    - name: Upload Test Results (Optional)
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: my-build-artifact
        path: ./path/to/your/artifacts
